---
repositories:
  - slug: thoth-station/common
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - goern
            - fridex
            - pacospace
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/analyzer
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/python
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - fridex
            - goern
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/storages
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - goern
            - fridex
            - pacospace
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/solver
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/lab
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - goern
            - fridex
            - harshad16
            - pacospace
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/adviser
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/graph-refresh-job
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/graph-sync-job
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/package-extract
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/package-releases-job
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/user-api
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/management-api
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - fridex
            - goern
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/messaging
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - goern
            - fridex
            - pacospace
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/thamos
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - goern
            - fridex
            - pacospace
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/kebechet
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/jupyter-notebook
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/init-job
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info

  - slug: thoth-station/graph-backup-job
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info

  - slug: thoth-station/srcops-testing
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]

  - slug: thoth-station/cve-update-job
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info

  - slug: thoth-station/invectio
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/amun-api
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info

  - slug: thoth-station/amun-client
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - fridex
            - goern
            - pacospace
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/metrics-exporter
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - fridex
            - goern
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/build-watcher
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info

  - slug: thoth-station/stub-api
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - goern
            - harshad16
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: false

  - slug: thoth-station/thoth-pybench
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - pacospace
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: false

  - slug: thoth-station/s2i-thoth
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: version
        configuration:
          maintainers:
            - sesheta
            - harshad16
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: false

  - slug: thoth-station/s2i
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: info
      - name: update
        configuration:
          labels: [bot]
      - name: version
        configuration:
          maintainers:
            - sesheta
            - harshad16
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: false

  - slug: thoth-station/package-update-job
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info

  - slug: thoth-station/unresolved-package-handler
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: info
      - name: update
        configuration:
          labels: [bot]

  - slug: thoth-station/advise-reporter
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - harshad16
            - goern
            - fridex
            - pacospace
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true
      - name: update
        configuration:
          labels: [bot]

  - slug: thoth-station/s2i-tensorflow-notebook
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: info
      - name: update
        configuration:
          labels: [bot]

  - slug: thoth-station/s2i-scipy-notebook
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: info
      - name: update
        configuration:
          labels: [bot]

  - slug: thoth-station/s2i-minimal-notebook
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: info
      - name: update
        configuration:
          labels: [bot]

  - slug: thoth-station/slo-reporter
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - harshad16
            - goern
            - fridex
            - pacospace
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true
      - name: update
        configuration:
          labels: [bot]

  - slug: thoth-station/source-management
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - harshad16
            - goern
            - fridex
            - saisankargochhayat
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true
      - name: update
        configuration:
          labels: [bot]

  - slug: thoth-station/workflow-helpers
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - fridex
            - goern
            - harshad16
            - pacospace
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/datasets
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - harshad16
            - goern
            - fridex
            - pacospace
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true
      - name: update
        configuration:
          labels: [bot]

  - slug: thoth-station/solver-error-classifier
    token: "{KEBECHET_TOKEN}"
    managers:
      - name: info
      - name: version
        configuration:
          maintainers:
            - sesheta
            - harshad16
            - goern
            - fridex
            - pacospace
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true
      - name: update
        configuration:
          labels: [bot]
