---
repositories:
  - &update_config
    slug: thoth-station/adviser
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
  - <<: *update_config
    slug: thoth-station/analyzer
  - <<: *update_config
    slug: thoth-station/cleanup-job
  - <<: *update_config
    slug: thoth-station/common
  - <<: *update_config
    slug: thoth-station/graph-refresh-job
  - <<: *update_config
    slug: thoth-station/graph-sync-job
  - <<: *update_config
    slug: thoth-station/lab
  - <<: *update_config
    slug: thoth-station/package-extract
  - <<: *update_config
    slug: thoth-station/package-releases-job
  - <<: *update_config
    slug: thoth-station/result-api
  - <<: *update_config
    slug: thoth-station/solver
  - <<: *update_config
    slug: thoth-station/storages
  - <<: *update_config
    slug: thoth-station/user-api
  - <<: *update_config
    slug: thoth-station/kebechet
  - <<: *update_config
    slug: thoth-station/jupyter-notebook
  - <<: *update_config
    slug: thoth-station/sesheta
