---
repositories:
  - &update_config
    slug: thoth-station/adviser
    labels:
      - bot
    managers:
      - update
  - <<: *update_config
    slug: thoth-station/analyzer
  - <<: *update_config
    slug: thoth-station/cleanup-job
  - <<: *update_config
    slug: thoth-station/common
  - <<: *update_config
    slug: thoth-station/graph-refresh-job
  - <<: *update_config
    slug: thoth-station/graph-sync-job
  - <<: *update_config
    slug: thoth-station/lab
  - <<: *update_config
    slug: thoth-station/package-extract
  - <<: *update_config
    slug: thoth-station/package-releases-job
  - <<: *update_config
    slug: thoth-station/result-api
  - <<: *update_config
    slug: thoth-station/solver
  - <<: *update_config
    slug: thoth-station/storages
  - <<: *update_config
    slug: thoth-station/user-api
  - <<: *update_config
    slug: thoth-station/kebechet
  - <<: *update_config
    slug: thoth-station/jupyter-notebook
