---
repositories:
  - slug: thoth-station/adviser
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/build-analyzers
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - cermakM
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/analyzer
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/cleanup-job
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/common
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/graph-refresh-job
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/graph-sync-job
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/graph-sync-scheduler
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info

  - slug: thoth-station/lab
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
            - CermakM
            - harshad16
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/package-extract
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/python
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - fridex
            - goern
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/package-releases-job
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/result-api
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/solver
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/storages
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
            - pacospace
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/user-api
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/management-api
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - fridex
            - goern
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/kebechet
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/jupyter-notebook
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/init-job
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info

  - slug: thoth-station/sesheta
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]

  - slug: thoth-station/srcops-testing
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]

  - slug: thoth-station/cve-update-job
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info

  - slug: thoth-station/graph-sync-operator
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]

  - slug: thoth-station/workload-operator
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]

  - slug: thoth-station/thamos
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/invectio
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/amun-api
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info

  - slug: thoth-station/amun-client
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - fridex
            - goern
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: user-cont/conu
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: 
            - bot
            - thoth-station
            - kebechet

  - slug: AICoE/log-anomaly-detector
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info

  - slug: AICoE/prometheus-flatliner
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info

  - slug: thoth-station/metrics-exporter
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - fridex
            - goern
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/build-watcher
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
