---
- name: Playbook to deprovision Thoth's Kebechet Bot deployment
  tags:
    - openshift
    - thoth
    - kebechet
    - bot

  hosts: localhost
  vars:
    OPENSHIFT_MASTER_URL: "{{ lookup('env','OCP_URL') }}"
    OPENSHIFT_AUTH_TOKEN: "{{ lookup('env','OCP_TOKEN') }}"

    KEBECHET_APPLICATION_NAMESPACE: "{{ lookup('env','KEBECHET_APPLICATION_NAMESPACE') }}"
    KEBECHET_INFRA_NAMESPACE: "{{ lookup('env','KEBECHET_INFRA_NAMESPACE') }}"

  gather_facts: false
  connection: local

  tasks:
  - name: login to OpenShift using provided token
    command: "oc login {{ OCP_URL }} --insecure-skip-tls-verify=true --token {{ OCP_TOKEN }}"
    changed_when: False

  - name: "deleting Objects"
    command: "oc delete {{ item }} --namespace {{ KEBECHET_APPLICATION_NAMESPACE }}"
    with_items:
      - "secret/kebechet-secret"
      - "configmap/kebechet-configmap"
      - "buildconfig/kebechet-job"
      - "cronjob/kebechet"

  - name: "deleting Objects"
    command: "oc delete {{ item }} --namespace {{ KEBECHET_INFRA_NAMESPACE }}"
    with_items:
      - "imagestreams/kebechet-job"
      - "template/kebechet-imagestream"
      - "template/kebechet-buildconfig"
      - "template/kebechet-cronjob"
